### ISSUE TITLE
API url not compliant 

### ISSUE THREAD

**Issue by ivarconr** [stiano/unleash-client-dotnet#11]
It would be preferable to have this client accepting `http://unleash.herokuapp.com/api/` as URL for Unleash to align with other Unleash clients.

**Comment by ivarconr** [comment]
@stiano any thoughts on this? 

I was thinking that the client should just accept both `http://some-host.com/api/` and `http://some-host.com/`. 

This will make this SDK consistent with all other SDKs.

**Comment by stiano** [comment]
@ivarconr

I agree, I will add this for the next release.

**Comment by ivarconr** [comment]
https://github.com/Unleash/unleash-client-core
