### ISSUE TITLE
Is InstanceTag the same as InstanceId in other clients?

### ISSUE THREAD

**Issue by bjarki** [stiano/unleash-client-dotnet#15]
I'm trying to use this client with Gitlab.com as an Unleash server. 

But the requests add `/api/` to the URL. Gitlab, for example, is not using that in their path.

The request from the client

`https://gitlab.com/api/v4/feature_flags/unleash/1234/api/client/features `

The correct request
`https://gitlab.com/api/v4/feature_flags/unleash/1234/client/features `

The issue is the  `const` strings in `UnleashApiClient.cs`

```csharp
      const string resourceUri = "api/client/features";
```

Can we add a way to overwrite them or some way to get around this?

**Comment by stiano** [comment]
@bjarki 

InstanceTag & InstanceId should be the same, yes.

There is planned a change for the /api/ concern you have. Until then, you can implement the Unleash version of IHttpClientFactory interface, and there provide a HttpClient that have an inner DelegatingHandler which modifies the request uri before sending the actual request. Something like e.g. [this](https://thomaslevesque.com/2016/12/08/fun-with-the-httpclient-pipeline/). 

Hope this helps.

**Comment by bjarki** [comment]
Thanks for the help @stiano 

Here is my workaround
```csharp
    public class GitlabUnleashHttpClientFactory : IHttpClientFactory
    {
        public HttpClient Create(Uri unleashApiUri)
        {
            var deli = new GitlabUnleashHttpMessageHandler
            {
                InnerHandler = new HttpClientHandler()
            };

            return new HttpClient(deli)
            {
                BaseAddress = unleashApiUri
            };
        }
    }

    /// <summary>
    /// Will replace the last instans of api/ in the request to work with Gitlab
    /// </summary>
    public class GitlabUnleashHttpMessageHandler : DelegatingHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var oldUri = request.RequestUri.ToString();
            var updatedUri = ReplaceLastOccurrence(oldUri, "api/", string.Empty);
            var newUri = new Uri(updatedUri);
            request.RequestUri = newUri;

            return base.SendAsync(request, cancellationToken);
        }

        public static string ReplaceLastOccurrence(string source, string find, string replace)
        {
            int place = source.LastIndexOf(find);

            if (place == -1)
                return source;

            string result = source.Remove(place, find.Length).Insert(place, replace);
            return result;
        }
    }

```
