### ISSUE TITLE
As a user, I would like to be able to fetch feature toggles synchronously during startup

### ISSUE THREAD

**Issue by mortenmj** [stiano/unleash-client-dotnet#16]
The Java client for Unleash (https://github.com/Unleash/unleash-client-java) has a flag in UnleashSettings called synchronousFetchOnInitialisation. 
Currently, even though feature toggles can be fetched on startup (and are by default), it is not done synchronously.

Expected behavior is to have feature flags loaded immediately after instantiating DefaultUnleash. Observed behavior is that feature flags are loaded in the background, and available some time later. As far as I can tell, use of feature flags on startup requires a short sleep after calling DefaultUnleash, which is unpleasant and racecondition-y.

**Comment by scottt732** [comment]
+1 on this.  I would like to explicitly ask for & wait for the settings to load, retry if necessary, and crash the process if there's an issue... before ASP.NET Core/Kestrel even begins listening for incoming HTTP connections (see [here](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-3/)).

I'm concerned about a transient issue at a critical point in app startup causing the application to regress to a state where every feature flag returns its default value/anything unusual.

**Comment by ivarconr** [comment]
@mortenmj can you direct this issue in https://github.com/Unleash/unleash-client-core? We already support this in the Java SDK, and feels natural to also have the same options for the .net

**Comment by mortenmj** [comment]
Fixed in https://github.com/Unleash/unleash-client-dotnet/issues/50
