### ISSUE TITLE
Move this repo to Unleash org?

### ISSUE THREAD

**Issue by ivarconr** [stiano/unleash-client-dotnet#8]
Hi, what do you think about moving this repo to the Unleash organisation
(https://github.com/Unleash). It will be easier for me and my team to contribute having it all under the same organisation. 

The last effort stranded a bit (https://github.com/Unleash/unleash-client-core/issues/1) and I think it is better to have this one as a starting-point. It seems to have more traction than the other .Net client.  We can always iterate the code.

**Comment by ivarconr** [comment]
what do you think @stiano ?

**Comment by ivarconr** [comment]
ping

**Comment by stiano** [comment]
Hi, sorry for late reply. 
I am not comfortable handing over the code you guys just like that.
I could however agree to add people from your team as collaborators to this github and AppVeyor project. This will give your team all the tools necessary to co-maintain this project.

**Comment by ivarconr** [comment]
My intention was not to take over the project, more of hosting it together under the same umbrella and hopefully increase the discover-ability of the client. You would of course remain core maintainer of the client. Actually multiple of the clients maintained by specific persons.

But of course if you prefer to keep it under your personal GitHub account I respect that too. It's up to you. 

Anyways it's awesome all the effort you have done and that you want to keep maintaining the client. 

We have started to introduce variant support with implementations in few of the clients already (Java, Node.js and Go in progress). I will share with you the  specifications on how to implement the client support soon.
